language: node_js
node_js:
- 6.9.0
install:
  - npm i -g npm@3
  - npm install
script:
  - npm run eslint
  - npm run test
cache:
  directories:
  - node_modules
branches:
  only:
  - master
